import type { PathRegistryInput } from '../db/pathRegistry.js';

export const BUILTIN_PATHS: PathRegistryInput[] = [
  // ── Claude Desktop ──────────────────────────────────────────────
  {
    id: 'claude-desktop-mac-mcp',
    label: 'Claude Desktop — MCP config (macOS)',
    path: '~/Library/Application Support/Claude/claude_desktop_config.json',
    type: 'mcp-config',
    agent: 'claude-desktop',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 100,
  },
  {
    id: 'claude-desktop-linux-mcp',
    label: 'Claude Desktop — MCP config (Linux)',
    path: '$XDG_CONFIG_HOME/Claude/claude_desktop_config.json',
    type: 'mcp-config',
    agent: 'claude-desktop',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 101,
  },
  {
    id: 'claude-desktop-mac-skills',
    label: 'Claude Desktop — skills (macOS)',
    path: '~/Library/Application Support/Claude/skills',
    type: 'skills-dir',
    agent: 'claude-desktop',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 102,
  },
  {
    id: 'claude-desktop-linux-skills',
    label: 'Claude Desktop — skills (Linux)',
    path: '$XDG_CONFIG_HOME/Claude/skills',
    type: 'skills-dir',
    agent: 'claude-desktop',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 103,
  },

  // ── Claude Code (CLI) ──────────────────────────────────────────
  {
    id: 'claude-code-global-settings',
    label: 'Claude Code — global settings',
    path: '~/.claude/settings.json',
    type: 'mcp-config',
    agent: 'claude-code',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 200,
  },
  {
    id: 'claude-code-global-mcp',
    label: 'Claude Code — global MCP',
    path: '~/.claude/mcp.json',
    type: 'mcp-config',
    agent: 'claude-code',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 201,
  },
  {
    id: 'claude-code-global-claude-md',
    label: 'Claude Code — global instructions',
    path: '~/.claude/CLAUDE.md',
    type: 'skills-dir',
    agent: 'claude-code',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 202,
  },
  {
    id: 'claude-code-global-commands',
    label: 'Claude Code — global commands',
    path: '~/.claude/skills',
    type: 'skills-dir',
    agent: 'claude-code',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 203,
  },
  {
    id: 'claude-code-project-settings',
    label: 'Claude Code — project settings',
    path: '.claude/settings.json',
    type: 'mcp-config',
    agent: 'claude-code',
    scope: 'project',
    source: 'builtin',
    enabled: true,
    sort_order: 204,
  },
  {
    id: 'claude-code-project-commands',
    label: 'Claude Code — project commands',
    path: '.claude/skills',
    type: 'skills-dir',
    agent: 'claude-code',
    scope: 'project',
    source: 'builtin',
    enabled: true,
    sort_order: 205,
  },

  // ── Cursor ─────────────────────────────────────────────────────
  {
    id: 'cursor-global-mcp',
    label: 'Cursor — global MCP',
    path: '~/.cursor/mcp.json',
    type: 'mcp-config',
    agent: 'cursor',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 300,
  },
  {
    id: 'cursor-project-mcp',
    label: 'Cursor — project MCP',
    path: '.cursor/mcp.json',
    type: 'mcp-config',
    agent: 'cursor',
    scope: 'project',
    source: 'builtin',
    enabled: true,
    sort_order: 301,
  },
  {
    id: 'cursor-global-rules',
    label: 'Cursor — global rules',
    path: '~/.cursor/rules',
    type: 'skills-dir',
    agent: 'cursor',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 302,
  },
  {
    id: 'cursor-project-rules',
    label: 'Cursor — project rules',
    path: '.cursor/rules',
    type: 'skills-dir',
    agent: 'cursor',
    scope: 'project',
    source: 'builtin',
    enabled: true,
    sort_order: 303,
  },

  // ── Windsurf ───────────────────────────────────────────────────
  {
    id: 'windsurf-global-mcp',
    label: 'Windsurf — global MCP (codeium)',
    path: '~/.codeium/windsurf/mcp_config.json',
    type: 'mcp-config',
    agent: 'windsurf',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 400,
  },
  {
    id: 'windsurf-global-mcp-new',
    label: 'Windsurf — global MCP',
    path: '~/.windsurf/mcp.json',
    type: 'mcp-config',
    agent: 'windsurf',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 401,
  },
  {
    id: 'windsurf-project-mcp',
    label: 'Windsurf — project MCP',
    path: '.windsurf/mcp.json',
    type: 'mcp-config',
    agent: 'windsurf',
    scope: 'project',
    source: 'builtin',
    enabled: true,
    sort_order: 402,
  },
  {
    id: 'windsurf-global-rules',
    label: 'Windsurf — global rules',
    path: '~/.codeium/windsurf/rules',
    type: 'skills-dir',
    agent: 'windsurf',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 403,
  },

  // ── VS Code + Copilot ──────────────────────────────────────────
  {
    id: 'vscode-copilot-mac-settings',
    label: 'VS Code — user settings (macOS)',
    path: '~/Library/Application Support/Code/User/settings.json',
    type: 'mcp-config',
    agent: 'vscode-copilot',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 500,
  },
  {
    id: 'vscode-copilot-linux-settings',
    label: 'VS Code — user settings (Linux)',
    path: '$XDG_CONFIG_HOME/Code/User/settings.json',
    type: 'mcp-config',
    agent: 'vscode-copilot',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 501,
  },
  {
    id: 'vscode-copilot-global-mcp',
    label: 'VS Code — global MCP',
    path: '~/.vscode/mcp.json',
    type: 'mcp-config',
    agent: 'vscode-copilot',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 502,
  },
  {
    id: 'vscode-copilot-project-mcp',
    label: 'VS Code — project MCP',
    path: '.vscode/mcp.json',
    type: 'mcp-config',
    agent: 'vscode-copilot',
    scope: 'project',
    source: 'builtin',
    enabled: true,
    sort_order: 503,
  },

  // ── Goose ──────────────────────────────────────────────────────
  {
    id: 'goose-config-xdg',
    label: 'Goose — config (XDG)',
    path: '$XDG_CONFIG_HOME/goose/config.yaml',
    type: 'mcp-config',
    agent: 'goose',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 600,
  },
  {
    id: 'goose-config-home',
    label: 'Goose — config (home)',
    path: '~/.goose/config.yaml',
    type: 'mcp-config',
    agent: 'goose',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 601,
  },

  // ── Cline ──────────────────────────────────────────────────────
  {
    id: 'cline-mac-mcp',
    label: 'Cline — MCP settings (macOS)',
    path: '~/Library/Application Support/Code/User/globalStorage/saoudrizwan.claude-dev/settings/cline_mcp_settings.json',
    type: 'mcp-config',
    agent: 'cline',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 700,
  },
  {
    id: 'cline-linux-mcp',
    label: 'Cline — MCP settings (Linux)',
    path: '$XDG_CONFIG_HOME/Code/User/globalStorage/saoudrizwan.claude-dev/settings/cline_mcp_settings.json',
    type: 'mcp-config',
    agent: 'cline',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 701,
  },

  // ── Roo Code ───────────────────────────────────────────────────
  {
    id: 'roo-code-mac-mcp',
    label: 'Roo Code — MCP settings (macOS)',
    path: '~/Library/Application Support/Code/User/globalStorage/rooveterinaryinc.roo-cline/settings/mcp_settings.json',
    type: 'mcp-config',
    agent: 'roo-code',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 800,
  },
  {
    id: 'roo-code-linux-mcp',
    label: 'Roo Code — MCP settings (Linux)',
    path: '$XDG_CONFIG_HOME/Code/User/globalStorage/rooveterinaryinc.roo-cline/settings/mcp_settings.json',
    type: 'mcp-config',
    agent: 'roo-code',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 801,
  },

  // ── Continue ───────────────────────────────────────────────────
  {
    id: 'continue-global-config',
    label: 'Continue — global config',
    path: '~/.continue/config.json',
    type: 'mcp-config',
    agent: 'continue',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 900,
  },
  {
    id: 'continue-project-config',
    label: 'Continue — project config',
    path: '.continue/config.json',
    type: 'mcp-config',
    agent: 'continue',
    scope: 'project',
    source: 'builtin',
    enabled: true,
    sort_order: 901,
  },
  {
    id: 'continue-global-skills',
    label: 'Continue — global skills',
    path: '~/.continue/skills',
    type: 'skills-dir',
    agent: 'continue',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 902,
  },
  {
    id: 'continue-project-skills',
    label: 'Continue — project skills',
    path: '.continue/skills',
    type: 'skills-dir',
    agent: 'continue',
    scope: 'project',
    source: 'builtin',
    enabled: true,
    sort_order: 903,
  },

  // ── Aider ──────────────────────────────────────────────────────
  {
    id: 'aider-config',
    label: 'Aider — config',
    path: '~/.aider/config.yml',
    type: 'mcp-config',
    agent: 'aider',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 1000,
  },
  {
    id: 'aider-conf',
    label: 'Aider — dotfile config',
    path: '~/.aider.conf.yml',
    type: 'mcp-config',
    agent: 'aider',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 1001,
  },
  {
    id: 'aider-conventions',
    label: 'Aider — conventions',
    path: '~/.aider/conventions',
    type: 'skills-dir',
    agent: 'aider',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 1002,
  },

  // ── Zed ────────────────────────────────────────────────────────
  {
    id: 'zed-mac-settings',
    label: 'Zed — settings (macOS)',
    path: '~/Library/Application Support/Zed/settings.json',
    type: 'mcp-config',
    agent: 'zed',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 1100,
  },
  {
    id: 'zed-linux-settings',
    label: 'Zed — settings (Linux)',
    path: '$XDG_CONFIG_HOME/zed/settings.json',
    type: 'mcp-config',
    agent: 'zed',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 1101,
  },
  {
    id: 'zed-mac-prompts',
    label: 'Zed — prompts (macOS)',
    path: '~/Library/Application Support/Zed/prompts',
    type: 'skills-dir',
    agent: 'zed',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 1102,
  },
  {
    id: 'zed-linux-prompts',
    label: 'Zed — prompts (Linux)',
    path: '$XDG_CONFIG_HOME/zed/prompts',
    type: 'skills-dir',
    agent: 'zed',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 1103,
  },

  // ── Trae ───────────────────────────────────────────────────────
  {
    id: 'trae-global-mcp',
    label: 'Trae — global MCP',
    path: '~/.trae/mcp.json',
    type: 'mcp-config',
    agent: 'trae',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 1200,
  },
  {
    id: 'trae-project-mcp',
    label: 'Trae — project MCP',
    path: '.trae/mcp.json',
    type: 'mcp-config',
    agent: 'trae',
    scope: 'project',
    source: 'builtin',
    enabled: true,
    sort_order: 1201,
  },

  // ── OpenCode ───────────────────────────────────────────────────
  {
    id: 'opencode-config',
    label: 'OpenCode — config',
    path: '$XDG_CONFIG_HOME/opencode/opencode.json',
    type: 'mcp-config',
    agent: 'opencode',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 1300,
  },

  // ── Augment Code ───────────────────────────────────────────────
  {
    id: 'augment-config',
    label: 'Augment Code — config',
    path: '~/.augment/config.json',
    type: 'mcp-config',
    agent: 'augment',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 1400,
  },

  // ── Amazon Q Developer ─────────────────────────────────────────
  {
    id: 'amazon-q-mcp',
    label: 'Amazon Q Developer — MCP',
    path: '~/.aws/amazonq/mcp.json',
    type: 'mcp-config',
    agent: 'amazon-q',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 1500,
  },

  // ── GitHub Copilot CLI ─────────────────────────────────────────
  {
    id: 'copilot-cli-hosts',
    label: 'GitHub Copilot CLI — hosts',
    path: '$XDG_CONFIG_HOME/github-copilot/hosts.json',
    type: 'mcp-config',
    agent: 'github-copilot-cli',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 1600,
  },

  // ── Supermaven ─────────────────────────────────────────────────
  {
    id: 'supermaven-config',
    label: 'Supermaven — config',
    path: '$XDG_CONFIG_HOME/supermaven/config.json',
    type: 'mcp-config',
    agent: 'supermaven',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 1700,
  },

  // ── Tabnine ────────────────────────────────────────────────────
  {
    id: 'tabnine-config',
    label: 'Tabnine — config',
    path: '$XDG_CONFIG_HOME/tabnine/tabnine_config.json',
    type: 'mcp-config',
    agent: 'tabnine',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 1800,
  },

  // ── JetBrains AI ───────────────────────────────────────────────
  {
    id: 'jetbrains-mcp',
    label: 'JetBrains — MCP config',
    path: '$XDG_CONFIG_HOME/JetBrains/mcp.json',
    type: 'mcp-config',
    agent: 'jetbrains',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 1900,
  },
  {
    id: 'jetbrains-ai-settings',
    label: 'JetBrains AI — settings',
    path: '$XDG_CONFIG_HOME/JetBrains/ai/settings.json',
    type: 'mcp-config',
    agent: 'jetbrains',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 1901,
  },

  // ── Warp AI ────────────────────────────────────────────────────
  {
    id: 'warp-agent-config',
    label: 'Warp AI — agent config',
    path: '~/.warp/agent/config.json',
    type: 'mcp-config',
    agent: 'warp',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 2000,
  },

  // ── Void ───────────────────────────────────────────────────────
  {
    id: 'void-global-mcp',
    label: 'Void — global MCP',
    path: '~/.void/mcp.json',
    type: 'mcp-config',
    agent: 'void',
    scope: 'global',
    source: 'builtin',
    enabled: true,
    sort_order: 2100,
  },
  {
    id: 'void-project-mcp',
    label: 'Void — project MCP',
    path: '.void/mcp.json',
    type: 'mcp-config',
    agent: 'void',
    scope: 'project',
    source: 'builtin',
    enabled: true,
    sort_order: 2101,
  },

  // ── Generic project-level ──────────────────────────────────────
  {
    id: 'project-mcp-json',
    label: 'Project — .mcp.json',
    path: '.mcp.json',
    type: 'mcp-config',
    agent: null,
    scope: 'project',
    source: 'builtin',
    enabled: true,
    sort_order: 9000,
  },
  {
    id: 'project-claude-md',
    label: 'Project — CLAUDE.md',
    path: 'CLAUDE.md',
    type: 'skills-dir',
    agent: 'claude-code',
    scope: 'project',
    source: 'builtin',
    enabled: true,
    sort_order: 9001,
  },
];
