import type { PathRegistryInput } from '../db/pathRegistry.js';

type Kind = PathRegistryInput['type'];
type Scope = PathRegistryInput['scope'];

/**
 * Built-in path entries, grouped by agent (see `agents.ts` for agent metadata).
 * Ids are persisted in users' registries: renaming one resets that entry's
 * enabled flag, so prefer adding new ids over changing existing ones.
 *
 * Path syntax: `~` and `$HOME` (home dir), `$XDG_CONFIG_HOME` (defaults to
 * ~/.config), `{WIN_HOME}` (Windows profile, WSL only). Relative paths are
 * project-scoped and resolve against the scanned working directory.
 */
const ENTRIES: [
  agent: string | null,
  id: string,
  label: string,
  path: string,
  type: Kind,
  scope: Scope,
][] = [
  // Claude Code
  [
    'claude-code',
    'claude-code-user-mcp',
    'Claude Code — user MCP servers',
    '~/.claude.json',
    'mcp-config',
    'global',
  ],
  [
    'claude-code',
    'claude-code-project-mcp',
    'Claude Code — project MCP servers',
    '.mcp.json',
    'mcp-config',
    'project',
  ],
  [
    'claude-code',
    'claude-code-global-commands',
    'Claude Code — user skills',
    '~/.claude/skills',
    'skills-dir',
    'global',
  ],
  [
    'claude-code',
    'claude-code-project-commands',
    'Claude Code — project skills',
    '.claude/skills',
    'skills-dir',
    'project',
  ],
  // Claude Desktop
  [
    'claude-desktop',
    'claude-desktop-mac-mcp',
    'Claude Desktop — MCP config (macOS)',
    '~/Library/Application Support/Claude/claude_desktop_config.json',
    'mcp-config',
    'global',
  ],
  [
    'claude-desktop',
    'claude-desktop-wsl-mcp',
    'Claude Desktop — MCP config (Windows via WSL)',
    '{WIN_HOME}/AppData/Roaming/Claude/claude_desktop_config.json',
    'mcp-config',
    'global',
  ],
  // OpenAI Codex
  [
    'codex',
    'codex-global-config',
    'OpenAI Codex — user config',
    '~/.codex/config.toml',
    'mcp-config',
    'global',
  ],
  [
    'codex',
    'codex-project-config',
    'OpenAI Codex — project config',
    '.codex/config.toml',
    'mcp-config',
    'project',
  ],
  [
    'codex',
    'codex-global-skills',
    'OpenAI Codex — user skills (legacy)',
    '~/.codex/skills',
    'skills-dir',
    'global',
  ],
  // Google Antigravity
  [
    'antigravity',
    'antigravity-global-mcp',
    'Google Antigravity — MCP config',
    '~/.gemini/config/mcp_config.json',
    'mcp-config',
    'global',
  ],
  [
    'antigravity',
    'antigravity-legacy-mcp',
    'Google Antigravity — MCP config (legacy)',
    '~/.gemini/antigravity/mcp_config.json',
    'mcp-config',
    'global',
  ],
  [
    'antigravity',
    'antigravity-project-mcp',
    'Google Antigravity — workspace MCP config',
    '.agents/mcp_config.json',
    'mcp-config',
    'project',
  ],
  [
    'antigravity',
    'antigravity-global-skills',
    'Google Antigravity — user skills',
    '~/.gemini/config/skills',
    'skills-dir',
    'global',
  ],
  [
    'antigravity',
    'antigravity-cli-skills',
    'Google Antigravity — CLI skills',
    '~/.gemini/antigravity-cli/skills',
    'skills-dir',
    'global',
  ],
  [
    'antigravity',
    'antigravity-legacy-skills',
    'Google Antigravity — user skills (legacy)',
    '~/.gemini/antigravity/skills',
    'skills-dir',
    'global',
  ],
  // Gemini CLI (legacy)
  [
    'gemini-cli',
    'gemini-cli-global-settings',
    'Gemini CLI (legacy) — user settings',
    '~/.gemini/settings.json',
    'mcp-config',
    'global',
  ],
  [
    'gemini-cli',
    'gemini-cli-project-settings',
    'Gemini CLI (legacy) — project settings',
    '.gemini/settings.json',
    'mcp-config',
    'project',
  ],
  [
    'gemini-cli',
    'gemini-cli-global-skills',
    'Gemini CLI (legacy) — user skills',
    '~/.gemini/skills',
    'skills-dir',
    'global',
  ],
  [
    'gemini-cli',
    'gemini-cli-project-skills',
    'Gemini CLI (legacy) — project skills',
    '.gemini/skills',
    'skills-dir',
    'project',
  ],
  // GitHub Copilot CLI
  [
    'github-copilot-cli',
    'copilot-cli-global-mcp',
    'GitHub Copilot CLI — user MCP config',
    '~/.copilot/mcp-config.json',
    'mcp-config',
    'global',
  ],
  [
    'github-copilot-cli',
    'copilot-cli-project-mcp',
    'GitHub Copilot CLI — repository MCP config',
    '.github/mcp.json',
    'mcp-config',
    'project',
  ],
  [
    'github-copilot-cli',
    'copilot-global-skills',
    'GitHub Copilot CLI — user skills',
    '~/.copilot/skills',
    'skills-dir',
    'global',
  ],
  [
    'github-copilot-cli',
    'copilot-project-skills',
    'GitHub Copilot CLI — repository skills',
    '.github/skills',
    'skills-dir',
    'project',
  ],
  // VS Code (Copilot)
  [
    'vscode-copilot',
    'vscode-copilot-mac-mcp',
    'VS Code (Copilot) — user MCP config (macOS)',
    '~/Library/Application Support/Code/User/mcp.json',
    'mcp-config',
    'global',
  ],
  [
    'vscode-copilot',
    'vscode-copilot-linux-mcp',
    'VS Code (Copilot) — user MCP config (Linux)',
    '$XDG_CONFIG_HOME/Code/User/mcp.json',
    'mcp-config',
    'global',
  ],
  [
    'vscode-copilot',
    'vscode-copilot-project-mcp',
    'VS Code (Copilot) — workspace MCP config',
    '.vscode/mcp.json',
    'mcp-config',
    'project',
  ],
  // Cursor
  [
    'cursor',
    'cursor-global-mcp',
    'Cursor — user MCP config',
    '~/.cursor/mcp.json',
    'mcp-config',
    'global',
  ],
  [
    'cursor',
    'cursor-project-mcp',
    'Cursor — project MCP config',
    '.cursor/mcp.json',
    'mcp-config',
    'project',
  ],
  [
    'cursor',
    'cursor-global-skills',
    'Cursor — user skills',
    '~/.cursor/skills',
    'skills-dir',
    'global',
  ],
  [
    'cursor',
    'cursor-project-skills',
    'Cursor — project skills',
    '.cursor/skills',
    'skills-dir',
    'project',
  ],
  // Devin Desktop (Windsurf)
  [
    'windsurf',
    'devin-desktop-global-mcp',
    'Devin Desktop (Windsurf) — MCP config',
    '$XDG_CONFIG_HOME/devin/mcp_config.json',
    'mcp-config',
    'global',
  ],
  [
    'windsurf',
    'windsurf-global-mcp',
    'Devin Desktop (Windsurf) — MCP config (legacy Windsurf)',
    '~/.codeium/windsurf/mcp_config.json',
    'mcp-config',
    'global',
  ],
  [
    'windsurf',
    'devin-desktop-global-skills',
    'Devin Desktop (Windsurf) — user skills',
    '$XDG_CONFIG_HOME/devin/skills',
    'skills-dir',
    'global',
  ],
  [
    'windsurf',
    'windsurf-global-skills',
    'Devin Desktop (Windsurf) — user skills (legacy Windsurf)',
    '~/.codeium/windsurf/skills',
    'skills-dir',
    'global',
  ],
  [
    'windsurf',
    'devin-desktop-project-skills',
    'Devin Desktop (Windsurf) — project skills',
    '.devin/skills',
    'skills-dir',
    'project',
  ],
  [
    'windsurf',
    'windsurf-project-skills',
    'Devin Desktop (Windsurf) — project skills (legacy Windsurf)',
    '.windsurf/skills',
    'skills-dir',
    'project',
  ],
  // Kiro
  [
    'kiro',
    'kiro-global-mcp',
    'Kiro — user MCP config',
    '~/.kiro/settings/mcp.json',
    'mcp-config',
    'global',
  ],
  [
    'kiro',
    'kiro-project-mcp',
    'Kiro — workspace MCP config',
    '.kiro/settings/mcp.json',
    'mcp-config',
    'project',
  ],
  ['kiro', 'kiro-global-skills', 'Kiro — user skills', '~/.kiro/skills', 'skills-dir', 'global'],
  [
    'kiro',
    'kiro-project-skills',
    'Kiro — workspace skills',
    '.kiro/skills',
    'skills-dir',
    'project',
  ],
  // Amazon Q Developer
  [
    'amazon-q',
    'amazon-q-mcp',
    'Amazon Q Developer — MCP config (legacy mcp.json)',
    '~/.aws/amazonq/mcp.json',
    'mcp-config',
    'global',
  ],
  [
    'amazon-q',
    'amazon-q-project-mcp',
    'Amazon Q Developer — workspace MCP config (legacy mcp.json)',
    '.amazonq/mcp.json',
    'mcp-config',
    'project',
  ],
  // Cline
  [
    'cline',
    'cline-cli-mcp',
    'Cline — CLI MCP settings',
    '~/.cline/data/settings/cline_mcp_settings.json',
    'mcp-config',
    'global',
  ],
  [
    'cline',
    'cline-mac-mcp',
    'Cline — VS Code extension MCP settings (macOS)',
    '~/Library/Application Support/Code/User/globalStorage/saoudrizwan.claude-dev/settings/cline_mcp_settings.json',
    'mcp-config',
    'global',
  ],
  [
    'cline',
    'cline-linux-mcp',
    'Cline — VS Code extension MCP settings (Linux)',
    '$XDG_CONFIG_HOME/Code/User/globalStorage/saoudrizwan.claude-dev/settings/cline_mcp_settings.json',
    'mcp-config',
    'global',
  ],
  [
    'cline',
    'cline-global-skills',
    'Cline — user skills',
    '~/.cline/skills',
    'skills-dir',
    'global',
  ],
  [
    'cline',
    'cline-project-skills',
    'Cline — project skills',
    '.cline/skills',
    'skills-dir',
    'project',
  ],
  // Roo Code (archived)
  [
    'roo-code',
    'roo-code-mac-mcp',
    'Roo Code (archived) — MCP settings (macOS)',
    '~/Library/Application Support/Code/User/globalStorage/rooveterinaryinc.roo-cline/settings/mcp_settings.json',
    'mcp-config',
    'global',
  ],
  [
    'roo-code',
    'roo-code-linux-mcp',
    'Roo Code (archived) — MCP settings (Linux)',
    '$XDG_CONFIG_HOME/Code/User/globalStorage/rooveterinaryinc.roo-cline/settings/mcp_settings.json',
    'mcp-config',
    'global',
  ],
  [
    'roo-code',
    'roo-code-project-mcp',
    'Roo Code (archived) — project MCP config',
    '.roo/mcp.json',
    'mcp-config',
    'project',
  ],
  [
    'roo-code',
    'roo-code-global-skills',
    'Roo Code (archived) — user skills',
    '~/.roo/skills',
    'skills-dir',
    'global',
  ],
  [
    'roo-code',
    'roo-code-project-skills',
    'Roo Code (archived) — project skills',
    '.roo/skills',
    'skills-dir',
    'project',
  ],
  // Kilo Code
  [
    'kilo-code',
    'kilo-code-global-config',
    'Kilo Code — user config',
    '$XDG_CONFIG_HOME/kilo/kilo.jsonc',
    'mcp-config',
    'global',
  ],
  [
    'kilo-code',
    'kilo-code-project-config',
    'Kilo Code — project config',
    '.kilo/kilo.jsonc',
    'mcp-config',
    'project',
  ],
  // Continue
  [
    'continue',
    'continue-global-config',
    'Continue — user config',
    '~/.continue/config.yaml',
    'mcp-config',
    'global',
  ],
  [
    'continue',
    'continue-project-config',
    'Continue — workspace config',
    '.continue/config.yaml',
    'mcp-config',
    'project',
  ],
  // Zed
  [
    'zed',
    'zed-global-settings',
    'Zed — settings',
    '$XDG_CONFIG_HOME/zed/settings.json',
    'mcp-config',
    'global',
  ],
  [
    'zed',
    'zed-mac-settings',
    'Zed — settings (macOS legacy)',
    '~/Library/Application Support/Zed/settings.json',
    'mcp-config',
    'global',
  ],
  // opencode
  [
    'opencode',
    'opencode-config',
    'opencode — user config',
    '$XDG_CONFIG_HOME/opencode/opencode.json',
    'mcp-config',
    'global',
  ],
  [
    'opencode',
    'opencode-config-jsonc',
    'opencode — user config (JSONC)',
    '$XDG_CONFIG_HOME/opencode/opencode.jsonc',
    'mcp-config',
    'global',
  ],
  [
    'opencode',
    'opencode-project-config',
    'opencode — project config',
    'opencode.json',
    'mcp-config',
    'project',
  ],
  [
    'opencode',
    'opencode-global-skills',
    'opencode — user skills',
    '$XDG_CONFIG_HOME/opencode/skills',
    'skills-dir',
    'global',
  ],
  [
    'opencode',
    'opencode-project-skills',
    'opencode — project skills',
    '.opencode/skills',
    'skills-dir',
    'project',
  ],
  // Crush
  [
    'crush',
    'crush-global-config',
    'Crush — user config (JSON, deprecated)',
    '$XDG_CONFIG_HOME/crush/crush.json',
    'mcp-config',
    'global',
  ],
  [
    'crush',
    'crush-project-config',
    'Crush — project config (JSON, deprecated)',
    '.crush.json',
    'mcp-config',
    'project',
  ],
  [
    'crush',
    'crush-global-skills',
    'Crush — user skills',
    '$XDG_CONFIG_HOME/crush/skills',
    'skills-dir',
    'global',
  ],
  [
    'crush',
    'crush-project-skills',
    'Crush — project skills',
    '.crush/skills',
    'skills-dir',
    'project',
  ],
  // Amp
  [
    'amp',
    'amp-global-settings',
    'Amp — user settings',
    '$XDG_CONFIG_HOME/amp/settings.json',
    'mcp-config',
    'global',
  ],
  [
    'amp',
    'amp-project-settings',
    'Amp — workspace settings',
    '.amp/settings.json',
    'mcp-config',
    'project',
  ],
  [
    'amp',
    'amp-global-skills',
    'Amp — user skills',
    '$XDG_CONFIG_HOME/amp/skills',
    'skills-dir',
    'global',
  ],
  // Goose
  [
    'goose',
    'goose-config-xdg',
    'Goose — config',
    '$XDG_CONFIG_HOME/goose/config.yaml',
    'mcp-config',
    'global',
  ],
  [
    'goose',
    'goose-project-skills',
    'Goose — project skills',
    '.goose/skills',
    'skills-dir',
    'project',
  ],
  // Qwen Code
  [
    'qwen-code',
    'qwen-code-global-settings',
    'Qwen Code — user settings',
    '~/.qwen/settings.json',
    'mcp-config',
    'global',
  ],
  [
    'qwen-code',
    'qwen-code-project-settings',
    'Qwen Code — project settings',
    '.qwen/settings.json',
    'mcp-config',
    'project',
  ],
  // Factory Droid
  [
    'factory',
    'factory-global-mcp',
    'Factory Droid — user MCP config',
    '~/.factory/mcp.json',
    'mcp-config',
    'global',
  ],
  [
    'factory',
    'factory-project-mcp',
    'Factory Droid — project MCP config',
    '.factory/mcp.json',
    'mcp-config',
    'project',
  ],
  [
    'factory',
    'factory-global-skills',
    'Factory Droid — user skills',
    '~/.factory/skills',
    'skills-dir',
    'global',
  ],
  [
    'factory',
    'factory-project-skills',
    'Factory Droid — project skills',
    '.factory/skills',
    'skills-dir',
    'project',
  ],
  // Augment (Auggie)
  [
    'augment',
    'augment-settings',
    'Augment (Auggie) — CLI settings',
    '~/.augment/settings.json',
    'mcp-config',
    'global',
  ],
  // JetBrains Junie
  [
    'junie',
    'junie-global-mcp',
    'JetBrains Junie — user MCP config',
    '~/.junie/mcp/mcp.json',
    'mcp-config',
    'global',
  ],
  [
    'junie',
    'junie-project-mcp',
    'JetBrains Junie — project MCP config',
    '.junie/mcp/mcp.json',
    'mcp-config',
    'project',
  ],
  // Warp
  [
    'warp',
    'warp-global-mcp',
    'Warp — user MCP config',
    '~/.warp/.mcp.json',
    'mcp-config',
    'global',
  ],
  [
    'warp',
    'warp-project-mcp',
    'Warp — project MCP config',
    '.warp/.mcp.json',
    'mcp-config',
    'project',
  ],
  // Mistral Vibe
  [
    'mistral-vibe',
    'vibe-global-config',
    'Mistral Vibe — user config',
    '~/.vibe/config.toml',
    'mcp-config',
    'global',
  ],
  [
    'mistral-vibe',
    'vibe-project-config',
    'Mistral Vibe — project config',
    '.vibe/config.toml',
    'mcp-config',
    'project',
  ],
  [
    'mistral-vibe',
    'vibe-global-skills',
    'Mistral Vibe — user skills',
    '~/.vibe/skills',
    'skills-dir',
    'global',
  ],
  [
    'mistral-vibe',
    'vibe-project-skills',
    'Mistral Vibe — project skills',
    '.vibe/skills',
    'skills-dir',
    'project',
  ],
  // Kimi Code
  ['kimi', 'kimi-global-mcp', 'Kimi Code — MCP config', '~/.kimi/mcp.json', 'mcp-config', 'global'],
  // Grok Build
  [
    'grok',
    'grok-global-config',
    'Grok Build — user config',
    '~/.grok/config.toml',
    'mcp-config',
    'global',
  ],
  [
    'grok',
    'grok-project-config',
    'Grok Build — project config',
    '.grok/config.toml',
    'mcp-config',
    'project',
  ],
  [
    'grok',
    'grok-global-skills',
    'Grok Build — user skills',
    '~/.grok/skills',
    'skills-dir',
    'global',
  ],
  // Trae
  [
    'trae',
    'trae-mac-mcp',
    'Trae — MCP config (macOS)',
    '~/Library/Application Support/Trae/User/mcp.json',
    'mcp-config',
    'global',
  ],
  [
    'trae',
    'trae-project-mcp',
    'Trae — project MCP config',
    '.trae/mcp.json',
    'mcp-config',
    'project',
  ],
  // LM Studio
  [
    'lm-studio',
    'lm-studio-mcp',
    'LM Studio — MCP config',
    '~/.lmstudio/mcp.json',
    'mcp-config',
    'global',
  ],
  // Shared Agent Skills (.agents)
  [
    'agent-skills',
    'agent-skills-global',
    'Shared Agent Skills (.agents) — user skills (~/.agents)',
    '~/.agents/skills',
    'skills-dir',
    'global',
  ],
  [
    'agent-skills',
    'agent-skills-xdg',
    'Shared Agent Skills (.agents) — user skills (~/.config/agents)',
    '$XDG_CONFIG_HOME/agents/skills',
    'skills-dir',
    'global',
  ],
  [
    'agent-skills',
    'agent-skills-project',
    'Shared Agent Skills (.agents) — project skills (.agents)',
    '.agents/skills',
    'skills-dir',
    'project',
  ],
];

export const BUILTIN_PATHS: PathRegistryInput[] = ENTRIES.map(
  ([agent, id, label, path, type, scope], index) => ({
    id,
    label,
    path,
    type,
    agent,
    scope,
    source: 'builtin',
    enabled: true,
    sort_order: (index + 1) * 10,
  }),
);
