import {
  Monitor,
  Terminal,
  Code,
  MousePointer,
  Wind,
  Bird,
  Zap,
  ArrowRight,
  Rocket,
  Lock,
  Puzzle,
  Cloud,
  Github,
  Brain,
  Sparkles,
  Gem,
  Ghost,
  Waves,
  Feather,
  Flame,
  Hexagon,
  Cpu,
  Atom,
  Orbit,
  Boxes,
  Factory,
  Layers,
  FolderTree,
  Moon,
  Compass,
  Gauge,
  type LucideIcon,
} from 'lucide-react';

/** Icon per agent id (ids come from packages/backend/src/registry/agents.ts). */
export const AGENT_ICON_MAP: Record<string, LucideIcon> = {
  'claude-code': Terminal,
  'claude-desktop': Monitor,
  codex: Hexagon,
  antigravity: Orbit,
  'gemini-cli': Gem,
  'github-copilot-cli': Github,
  'vscode-copilot': Code,
  cursor: MousePointer,
  windsurf: Wind,
  kiro: Ghost,
  'amazon-q': Cloud,
  cline: Zap,
  'roo-code': Rocket,
  'kilo-code': Gauge,
  continue: ArrowRight,
  zed: Feather,
  opencode: Lock,
  crush: Sparkles,
  amp: Flame,
  goose: Bird,
  'qwen-code': Brain,
  factory: Factory,
  augment: Puzzle,
  junie: Atom,
  warp: Waves,
  'mistral-vibe': Layers,
  kimi: Moon,
  grok: Cpu,
  trae: Compass,
  'lm-studio': Boxes,
  'agent-skills': FolderTree,
};

export const DEFAULT_AGENT_ICON = Code;

export function getAgentIcon(agentId: string): LucideIcon {
  return AGENT_ICON_MAP[agentId] ?? DEFAULT_AGENT_ICON;
}
